version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: belomax-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    depends_on:
      - redis

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: belomax-consumer
    env_file:
      - .env
    command: python main.py
    volumes:
      - .:/app
    depends_on:
      - redis

volumes:
  redis_data:
